### ISSUE TITLE
Google article about Places KTX is old and tells to install old version (0.2.2) instead of new one (0.4.0)

### ISSUE THREAD

**Issue by MadRatSRP** [googlemaps/android-places-ktx#25]
![image](https://user-images.githubusercontent.com/29717217/100515618-78fe9780-318e-11eb-9ce1-72082d13e717.png)
https://developers.google.com/places/android-sdk/ktx - here is the link for the article

![image](https://user-images.githubusercontent.com/29717217/100515646-b2370780-318e-11eb-9931-60a6b405ed72.png)
also images links are broken

**Comment by geofferyj** [comment]
This is not fixed

On the documentation, it says to use "implementation 'com.google.**_places_**.android:places-ktx:0.4.0" as dependency, however, this dependency doesn't exist as it should be implementation 'com.google.**_maps_**.android:places-ktx:0.4.0'

**Comment by arriolac** [comment]
Thanks. The documentation should now reflect the correct group ID.
