### ISSUE TITLE
Support bidirectional cancellation for suspending requests

### ISSUE THREAD

**Issue by alexvanyo** [googlemaps/android-places-ktx#42]
Right now, the `await*` functions in `PlacesClient.kt` don't support propagating cancellation to the corresponding `Tasks`. 

The builders for `FetchPhotoRequest`, `FetchPlaceRequest`, `FindAutocompletePredictionsRequest` and `feedbackFindCurrentPlaceRequest` each take a `CancellationToken`, which can be used to cancel the underlying `Tasks` if/when the suspending functions are cancelled.

Version [`1.5.1`](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.5.1) of `kotlinx-coroutines-play-services` added some [overloads of `Task.await`](https://github.com/Kotlin/kotlinx.coroutines/commit/e81ce210eef465d8fa0097bd6e463202b0f3e253) to support bidirectional cancellation, which should provide some of the necessary plumbing.

I'm not entirely sure what the API should look like to support this, since the `await*` functions currently take fully-built `Requests` as opposed to the builders, so there isn't a direct opportunity for the library to set the `CancellationToken`. Ideally the consumer of the library needs to know nothing about `CancellationToken`s at all, so perhaps the existing `await*` and builder functions are superseded by `await*` functions that include the builder?

**Comment by arriolac** [comment]
Since the `CancellationToken` is set on the builder object of each request's builder, and the `CancellationToken` is available to each request, an `await*` function implementation can pass in the token to the overloaded `Task.await` function. 

For example:

```kotlin
public suspend fun PlacesClient.awaitFindAutocompletePredictions(
    request: FindAutocompletePredictionsRequest
): FindAutocompletePredictionsResponse =
    this.findAutocompletePredictions(request).await(request.cancellationToken)
```

Let me know if this captures the use case.

**Comment by alexvanyo** [comment]
Unfortunately I don't think so, since the `Task.await` overload takes a `CancellationTokenSource`, since that's the thing that can cancel the underlying token that the task has.

Something like this would work, and hide the `CancellationTokenSource` from the consumer:
```kotlin
public suspend fun PlacesClient.awaitFindAutocompletePredictions(
    actions: FindAutocompletePredictionsRequest.Builder.() -> Unit
): FindAutocompletePredictionsResponse {
    val cancellationTokenSource = CancellationTokenSource()
    val request = FindAutocompletePredictionsRequest.builder()
        .apply(actions)
        .setCancellationToken(cancellationTokenSource.token)
        .build()
    return this.findAutocompletePredictions(request).await(cancellationTokenSource)
}
```

**Comment by arriolac** [comment]
Gotcha. Perhaps a default argument that the caller can override would be a more flexible API?

```kotlin
public suspend fun PlacesClient.awaitFindAutocompletePredictions(
    cancellationTokenSource: CancellationTokenSource = CancellationTokenSource(),
    actions: FindAutocompletePredictionsRequest.Builder.() -> Unit
): FindAutocompletePredictionsResponse {
    val request = FindAutocompletePredictionsRequest.builder()
        .apply(actions)
        .setCancellationToken(cancellationTokenSource.token)
        .build()
    return this.findAutocompletePredictions(request).await(cancellationTokenSource)
}
```

**Comment by alexvanyo** [comment]
That'd be more flexible, but I'm not sure what the usefulness would be of allowing the caller to provide a different `CancellationTokenSource`.

If the caller is converting the `Task` to a `suspend fun`, I would guess that the "normal" coroutine cancellation mechanisms would be preferable to also allowing cancellation a different way by a caller-provided `CancellationTokenSource`.

**Comment by arriolac** [comment]
> If the caller is converting the Task to a suspend fun, I would guess that the "normal" coroutine cancellation mechanisms would be preferable to also allowing cancellation a different way by a caller-provided CancellationTokenSource.


Good point. Best to keep the API simple then and abstract `CancellationTokenSource` from the caller then. If for whatever reason customizing the `CancellationTokenSource` is desirable, that API can be added (I'm unable to come up with an example for this). 

As a side-effect of completing this task, the current `await*` APIs that take in fully constructed request objects should be deprecated in favor of the cancellable ones.

**Comment by alexvanyo** [comment]
I wonder if it also makes sense to deprecate the existing builder APIs as well?

Potentially not, I suppose a consumer could be using those and not using coroutines (perhaps RxJava or just the `Task` API directly)

**Comment by arriolac** [comment]
Yeah, I think the builder APIs are still useful for non-coroutine users.
